'use strict';

var gulp          = require('gulp');
var $             = require('gulp-load-plugins')();
var util          = require('util');
var through2      = require('through2');
var es            = require('event-stream');
var runSequence   = require('run-sequence');
var webpack       = require('webpack');
var fileinclude   = require('gulp-file-include');
var rename        = require('gulp-rename');
var settings      = require('./config/settings.js');
var argv          = require('minimist')(process.argv.slice(2));

// Settings
var release       = argv.release;
var outputPath    = release ? settings.prodOutput : settings.devOutput;
var webpackConfig = require('./config/webpack.config.js')(release);
var webpackStats;


// A bit hackish. This function can't be called until after the javascript task has been run
// because webpackStats is undefined until webpack has run.
function getHashed(entryPoint){
  var jsFile = webpackStats.assetsByChunkName[entryPoint];
  // ignore source maps ie 'file.js' will have a source map of 'file.js.map'
  if (util.isArray(jsFile)) {
    jsFile = jsFile.filter(function (filename) {
      return path.extname(filename).toLowerCase() === '.js'
    }).shift();
  }
  return jsFile;
}

// Clean up
// -----------------------------------------------------------------------------
gulp.task('clean', function(cb){
  var rimraf = require('rimraf');
  rimraf(outputPath, cb);
});


// Copy vendor files
// -----------------------------------------------------------------------------
// Use this task to copy assets (ie fonts) from node modules
gulp.task('vendor', function(){
  return es.merge(
    gulp.src('./node_modules/bootstrap-sass/assets/fonts/**')
      .pipe(gulp.dest(outputPath + '/fonts')),
    gulp.src('./node_modules/font-awesome/fonts/**')
      .pipe(gulp.dest(outputPath + '/fonts'))
  );
});


// Copy html files
// -----------------------------------------------------------------------------
gulp.task('html', ['javascript'], function(){

  var tplFilter     = $.filter('**/*.tpl.html', {restore: true});
  var htmlFilter    = $.filter('**/*.html', {restore: true});

  return gulp.src('./html/**/*')
    .pipe($.ignore.exclude("partials/**"))
    .pipe($.ignore.exclude("partials"))
    .pipe(tplFilter)
    .pipe(fileinclude())  // Compile html (tpl) templates
    .pipe(rename({
      extname: ""
     }))
    .pipe(rename({
      extname: ".html"
     }))
    .pipe(tplFilter.restore)
    .pipe(htmlFilter)
    .pipe(through2.obj(function (html, enc, cb) { // replace entry points with names generated by webpack
      var result = String(html.contents);
      for(var entry in webpackConfig.entry){
        result = result.replace(entry + settings.buildSuffix, getHashed(entry));
      }
      html.contents = new Buffer(result);
      this.push(html);
      cb();
    }))
    .pipe(!release ? $.util.noop() : $.htmlmin({
        removeComments: true,
        collapseWhitespace: true,
        minifyJS: true
    }))
    .pipe(htmlFilter.restore)
    .pipe(gulp.dest(outputPath));
});


// Create JavaScript bundle
// -----------------------------------------------------------------------------
gulp.task('javascript', function(cb){

  var bundler = webpack(webpackConfig);

  function bundle(err, stats){
    webpackStats = stats.toJson();
    if (err){
      throw new $.util.PluginError('webpack', err);
    }
    //$.util.log('[webpack]', stats.toString({colors: true}));
    cb();
  }
  bundler.run(bundle);
});


// Build the app from source code
// -----------------------------------------------------------------------------
gulp.task('build', ['clean'], function(cb){
  runSequence(['html'], cb);
});


// The default task
gulp.task('default', ['build']);
