import wrapper from "./constants_wrapper";


const  actionTypes = [

  // ACCOUNTS
  "ACCOUNTS_LOAD",
  "ACCOUNT_LOAD",
  "COURSE_ACCOUNTS",
  "SUB_ACCOUNTS",
  "COURSES",
  "UPDATE_ACCOUNT",
  "DELETE_USER_ROOT_ACCOUNT",
  "CREATE_SUB_ACCOUNT"
  //ADMINS
  "ACCOUNT_ADMINS",
  "REMOVE_ADMINS",
  //ANALYTICS
  "ACCOUNT_TERM_ANALYTICS",
  "ACCOUNT_CURRENT_ANALYTICS",
  "ACCOUNT_COMPLETED_ANALYTICS",
      //grades
  "ACCOUNT_TERM_ANALYTICS_GRADES",
  "ACCOUNT_CURRENT_ANALYTICS_GRADES",
  "ACCOUNT_COMPLETED_ANALYTICS_GRADES",
      //statistics
  "ACCOUNT_TERM_ANALYTICS_STATISTICS",
  "ACCOUNT_CURRENT_ANALYTICS_STATISTICS",
  "ACCOUNT_COMPLETED_ANALYTICS_STATISTICS",
      //course-level
  "COURSE_ANALYTICS",
  "COURSE_ANALYTICS_ASSIGNMENTS",
  "COURSE_ANALYTICS_STUDENT_ID",
  "COURSE_ANALYTICS_STUDENT_ASSIGNMENTS",
  "COURSE_ANALYTICS_STUDENT_MESSAGE",
  //EXTERNAL FEEDS
  "COURSE_EXTERNAL_FEEDS",
  "GROUP_EXTERNAL_FEEDS",
  "COURSE_EXTERNAL_FEED",
  "GROUP_EXTERNAL_FEED",
  // ASSIGNMENT GROUP
  "COURSE_ASSIGNMENT_GROUPS",
  "COURSE_ASSIGNMENT_SINGLE_GROUP",
  "COURSE_ASSIGNMENT_SINGLE_GROUP_EDIT",
  "COURSE_ASSIGNMENT_SINGLE_GROUP_DEL",
   //ASSIGNMENT OVERRIDE
  "LIST_OVERRIDE_ASSIGNMENT",
  "OVERRIDE_ASSIGNMENT",
  "LIST_OVERRIDE_ASSIGNMENT_GROUP",
  //ASSIGNMENTS
  "DELETE_ASSIGNMENT",
  "LIST_ASSIGNMENT",
  "SINGLE_ASSIGNMENT",
  "EDIT_ASSIGNMENT"

  //ASSIGNMENT OVERRIDE
  "OVERRIDE_ASSIGNMENT",
  "LIST_OVERRIDE_ASSIGNMENT",


  //Appointment Groups
  "LIST_APPOINTMENT_GROUPS"
  "CREATE_APPOINTMENT_ACCOUNT"
  "SINGLE_APPOINTMENT_GROUP"
  "UPDATE_APPOINTMENT"
  "DELETE_APPOINMENT_GROUP"
  "LIST_USER_PARTICIPANTS"
  "STUDENT_GROUP_PARTICIPANTS"
];

const asyncActionTypes = [];

export default wrapper(actionTypes, asyncActionTypes);
