import wrapper from "./constants_wrapper";

const actionTypes = [];
const asyncActionTypes = [

  // ACCOUNTS
  "ACCOUNTS_LOAD",

  //ADMINS
  "ACCOUNT_ADMINS",
  "REMOVE_ADMINS"

  //ANALYTICS
  "ACCOUNT_TERM_ANALYTICS",
  "ACCOUNT_CURRENT_ANALYTICS",
  "ACCOUNT_COMPLETED_ANALYTICS",
      //grades
  "ACCOUNT_TERM_ANALYTICS_GRADES",
  "ACCOUNT_CURRENT_ANALYTICS_GRADES",
  "ACCOUNT_COMPLETED_ANALYTICS_GRADES",
      //statistics
  "ACCOUNT_TERM_ANALYTICS_STATISTICS",
  "ACCOUNT_CURRENT_ANALYTICS_STATISTICS",
  "ACCOUNT_COMPLETED_ANALYTICS_STATISTICS",
      //course-level
  "COURSE_ANALYTICS",
  "COURSE_ANALYTICS_ASSIGNMENTS",
  "COURSE_ANALYTICS_STUDENT_ID",
  "COURSE_ANALYTICS_STUDENT_ASSIGNMENTS",
  "COURSE_ANALYTICS_STUDENT_MESSAGE",

  //EXTERNAL FEEDS
  "COURSE_EXTERNAL_FEEDS",
  "GROUP_EXTERNAL_FEEDS",
  "COURSE_EXTERNAL_FEED",
  "GROUP_EXTERNAL_FEED"

  // ASSIGNMENT GROUP
  "COURSE_ASSIGNMENT_GROUPS",
  "COURSE_ASSIGNMENT_SINGLE_GROUP",
  "COURSE_ASSIGNMENT_SINGLE_GROUP_EDIT"
  "COURSE_ASSIGNMENT_SINGLE_GROUP_DEL"

  //ASSIGNMENTS
  "DELETE_ASSIGNMENT",
  "LIST_ASSIGNMENT",
  "SINGLE_ASSIGNMENT",
  "EDIT_ASSIGNMENT"

  //ASSIGNMENT OVERRIDE
  "OVERRIDE_ASSIGNMENT",
  "LIST_OVERRIDE_ASSIGNMENT",



];

export default wrapper(actionTypes, asyncActionTypes);