
export default {
    "SEARCH_ACCOUNT_DOMAINS": { uri: function(){return "/api/v1/accounts/search"}, method: "GET" },
  "ACCOUNT_NOTIFICATION_USERS": { uri: function(account_id, user_id){return "/api/v1/accounts/" + account_id + "/users/" + user_id + "/account_notifications"}, method: "GET" },
  "ACCOUNT_NOTIFICATION_USER_CLOSE_NOTIFICATION": { uri: function(account_id, user_id, id){return "/api/v1/accounts/" + account_id + "/users/" + user_id + "/account_notifications/" + id}, method: "DELETE" },
  "ACCOUNT_NOTIFICATION_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/account_notifications"}, method: "POST" },
  "ACCOUNT_REPORT_AVAILABLE_REPORTS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/reports"}, method: "GET" },
  "ACCOUNT_REPORT_CREATE": { uri: function(account_id, report){return "/api/v1/accounts/" + account_id + "/reports/" + report}, method: "POST" },
  "ACCOUNT_REPORTS": { uri: function(account_id, report){return "/api/v1/accounts/" + account_id + "/reports/" + report}, method: "GET" },
  "ACCOUNT_REPORT_GET": { uri: function(account_id, report, id){return "/api/v1/accounts/" + account_id + "/reports/" + report + "/" + id}, method: "GET" },
  "ACCOUNT_REPORT_DELETE": { uri: function(account_id, report, id){return "/api/v1/accounts/" + account_id + "/reports/" + report + "/" + id}, method: "DELETE" },
  "ACCOUNTS": { uri: function(){return "/api/v1/accounts"}, method: "GET" },
  "ACCOUNT_COURSE_ACCOUNTS": { uri: function(){return "/api/v1/course_accounts"}, method: "GET" },
  "ACCOUNT_GET": { uri: function(id){return "/api/v1/accounts/" + id}, method: "GET" },
  "ACCOUNT_SUB_ACCOUNTS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/sub_accounts"}, method: "GET" },
  "ACCOUNT_COURSES": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/courses"}, method: "GET" },
  "ACCOUNT_UPDATE": { uri: function(id){return "/api/v1/accounts/" + id}, method: "PUT" },
  "ACCOUNT_REMOVE_USER": { uri: function(account_id, user_id){return "/api/v1/accounts/" + account_id + "/users/" + user_id}, method: "DELETE" },
  "SUB_ACCOUNT_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/sub_accounts"}, method: "POST" },
  "ADMIN_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/admins"}, method: "POST" },
  "ADMIN_DELETE": { uri: function(account_id, user_id){return "/api/v1/accounts/" + account_id + "/admins/" + user_id}, method: "DELETE" },
  "ADMINS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/admins"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_PARTICIPATION_DATA": { uri: function(account_id, term_id){return "/api/v1/accounts/" + account_id + "/analytics/terms/" + term_id + "/activity"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_PARTICIPATION_DATA_BY_CURRENT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/analytics/current/activity"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_PARTICIPATION_DATA_BY_COMPLETED": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/analytics/completed/activity"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_GRADE_DATA": { uri: function(account_id, term_id){return "/api/v1/accounts/" + account_id + "/analytics/terms/" + term_id + "/grades"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_GRADE_DATA_BY_CURRENT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/analytics/current/grades"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_GRADE_DATA_BY_COMPLETED": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/analytics/completed/grades"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_STATISTICS": { uri: function(account_id, term_id){return "/api/v1/accounts/" + account_id + "/analytics/terms/" + term_id + "/statistics"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_STATISTICS_BY_CURRENT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/analytics/current/statistics"}, method: "GET" },
  "GET_DEPARTMENT_LEVEL_STATISTICS_BY_COMPLETED": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/analytics/completed/statistics"}, method: "GET" },
  "GET_COURSE_LEVEL_PARTICIPATION_DATA": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/analytics/activity"}, method: "GET" },
  "GET_COURSE_LEVEL_ASSIGNMENT_DATA": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/analytics/assignments"}, method: "GET" },
  "GET_COURSE_LEVEL_STUDENT_SUMMARY_DATA": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/analytics/student_summaries"}, method: "GET" },
  "GET_USER_IN_A_COURSE_LEVEL_PARTICIPATION_DATA": { uri: function(course_id, student_id){return "/api/v1/courses/" + course_id + "/analytics/users/" + student_id + "/activity"}, method: "GET" },
  "GET_USER_IN_A_COURSE_LEVEL_ASSIGNMENT_DATA": { uri: function(course_id, student_id){return "/api/v1/courses/" + course_id + "/analytics/users/" + student_id + "/assignments"}, method: "GET" },
  "GET_USER_IN_A_COURSE_LEVEL_MESSAGING_DATA": { uri: function(course_id, student_id){return "/api/v1/courses/" + course_id + "/analytics/users/" + student_id + "/communication"}, method: "GET" },
  "EXTERNAL_FEEDS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/external_feeds"}, method: "GET" },
  "EXTERNAL_FEEDS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/external_feeds"}, method: "GET" },
  "EXTERNAL_FEED_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/external_feeds"}, method: "POST" },
  "EXTERNAL_FEED_CREATE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/external_feeds"}, method: "POST" },
  "EXTERNAL_FEED_DELETE": { uri: function(course_id, external_feed_id){return "/api/v1/courses/" + course_id + "/external_feeds/" + external_feed_id}, method: "DELETE" },
  "EXTERNAL_FEED_DELETE_BY_GROUPS_AND_GROUP": { uri: function(group_id, external_feed_id){return "/api/v1/groups/" + group_id + "/external_feeds/" + external_feed_id}, method: "DELETE" },
  "APPOINTMENT_GROUPS": { uri: function(){return "/api/v1/appointment_groups"}, method: "GET" },
  "APPOINTMENT_GROUP_CREATE": { uri: function(){return "/api/v1/appointment_groups"}, method: "POST" },
  "APPOINTMENT_GROUP_GET": { uri: function(id){return "/api/v1/appointment_groups/" + id}, method: "GET" },
  "APPOINTMENT_GROUP_UPDATE": { uri: function(id){return "/api/v1/appointment_groups/" + id}, method: "PUT" },
  "APPOINTMENT_GROUP_DELETE": { uri: function(id){return "/api/v1/appointment_groups/" + id}, method: "DELETE" },
  "APPOINTMENT_GROUP_USERS": { uri: function(id){return "/api/v1/appointment_groups/" + id + "/users"}, method: "GET" },
  "APPOINTMENT_GROUP_GROUPS": { uri: function(id){return "/api/v1/appointment_groups/" + id + "/groups"}, method: "GET" },
  "ASSIGNMENT_GROUPS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/assignment_groups"}, method: "GET" },
  "ASSIGNMENT_GROUPS_GET": { uri: function(course_id, assignment_group_id){return "/api/v1/courses/" + course_id + "/assignment_groups/" + assignment_group_id}, method: "GET" },
  "ASSIGNMENT_GROUPS_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/assignment_groups"}, method: "POST" },
  "ASSIGNMENT_GROUPS_UPDATE": { uri: function(course_id, assignment_group_id){return "/api/v1/courses/" + course_id + "/assignment_groups/" + assignment_group_id}, method: "PUT" },
  "ASSIGNMENT_GROUPS_DELETE": { uri: function(course_id, assignment_group_id){return "/api/v1/courses/" + course_id + "/assignment_groups/" + assignment_group_id}, method: "DELETE" },
  "ASSIGNMENT_DELETE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/assignments/" + id}, method: "DELETE" },
  "ASSIGNMENTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/assignments"}, method: "GET" },
  "ASSIGNMENTS_USERS": { uri: function(user_id, course_id){return "/api/v1/users/" + user_id + "/courses/" + course_id + "/assignments"}, method: "GET" },
  "ASSIGNMENTS_GET": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/assignments/" + id}, method: "GET" },
  "ASSIGNMENTS_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/assignments"}, method: "POST" },
  "ASSIGNMENTS_UPDATE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/assignments/" + id}, method: "PUT" },
  "ASSIGNMENT_OVERRIDES": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/overrides"}, method: "GET" },
  "ASSIGNMENT_OVERRIDE_GET": { uri: function(course_id, assignment_id, id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/overrides/" + id}, method: "GET" },
  "ASSIGNMENT_OVERRIDE_GROUP_ALIAS": { uri: function(group_id, assignment_id){return "/api/v1/groups/" + group_id + "/assignments/" + assignment_id + "/override"}, method: "GET" },
  "ASSIGNMENT_OVERRIDE_SECTION_ALIAS": { uri: function(course_section_id, assignment_id){return "/api/v1/sections/" + course_section_id + "/assignments/" + assignment_id + "/override"}, method: "GET" },
  "ASSIGNMENT_OVERRIDE_CREATE": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/overrides"}, method: "POST" },
  "ASSIGNMENT_OVERRIDE_UPDATE": { uri: function(course_id, assignment_id, id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/overrides/" + id}, method: "PUT" },
  "ASSIGNMENT_OVERRIDE_DELETE": { uri: function(course_id, assignment_id, id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/overrides/" + id}, method: "DELETE" },
  "ACCOUNT_AUTHORIZATION_CONFIGS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/authentication_providers"}, method: "GET" },
  "ACCOUNT_AUTHORIZATION_CONFIGS_BY_ACCOUNT_AUTHORIZATION_CONFIGS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs"}, method: "GET" },
  "ACCOUNT_AUTHORIZATION_CONFIG_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/authentication_providers"}, method: "POST" },
  "ACCOUNT_AUTHORIZATION_CONFIG_CREATE_BY_ACCOUNT_AUTHORIZATION_CONFIGS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs"}, method: "POST" },
  "ACCOUNT_AUTHORIZATION_CONFIG_UPDATE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/authentication_providers/" + id}, method: "PUT" },
  "ACCOUNT_AUTHORIZATION_CONFIG_UPDATE_BY_ACCOUNT_AUTHORIZATION_CONFIGS": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs/" + id}, method: "PUT" },
  "ACCOUNT_AUTHORIZATION_CONFIG_GET": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/authentication_providers/" + id}, method: "GET" },
  "ACCOUNT_AUTHORIZATION_CONFIG_GET_BY_ACCOUNT_AUTHORIZATION_CONFIGS": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs/" + id}, method: "GET" },
  "ACCOUNT_AUTHORIZATION_CONFIG_DELETE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/authentication_providers/" + id}, method: "DELETE" },
  "ACCOUNT_AUTHORIZATION_CONFIG_DELETE_BY_ACCOUNT_AUTHORIZATION_CONFIGS": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs/" + id}, method: "DELETE" },
  "ACCOUNT_AUTHORIZATION_CONFIG_GET_DISCOVERY_URL": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs/discovery_url"}, method: "GET" },
  "ACCOUNT_AUTHORIZATION_CONFIG_UPDATE_DISCOVERY_URL": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs/discovery_url"}, method: "PUT" },
  "ACCOUNT_AUTHORIZATION_CONFIG_DELETE_DISCOVERY_URL": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/account_authorization_configs/discovery_url"}, method: "DELETE" },
  "ACCOUNT_AUTHORIZATION_CONFIG_GET_SSO_SETTINGS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/sso_settings"}, method: "GET" },
  "ACCOUNT_AUTHORIZATION_CONFIG_UPDATE_SSO_SETTINGS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/sso_settings"}, method: "PUT" },
  "AUTHENTICATION_AUDIT_FOR_LOGIN": { uri: function(login_id){return "/api/v1/audit/authentication/logins/" + login_id}, method: "GET" },
  "AUTHENTICATION_AUDIT_FOR_ACCOUNT": { uri: function(account_id){return "/api/v1/audit/authentication/accounts/" + account_id}, method: "GET" },
  "AUTHENTICATION_AUDIT_FOR_USER": { uri: function(user_id){return "/api/v1/audit/authentication/users/" + user_id}, method: "GET" },
  "BOOKMARKS_BOOKMARKS": { uri: function(format){return "/api/v1/users/self/bookmarks(/.json)(." + format + ")"}, method: "GET" },
  "BOOKMARKS_BOOKMARK_CREATE": { uri: function(){return "/api/v1/users/self/bookmarks"}, method: "POST" },
  "BOOKMARKS_BOOKMARK_GET": { uri: function(id){return "/api/v1/users/self/bookmarks/" + id}, method: "GET" },
  "BOOKMARKS_BOOKMARK_UPDATE": { uri: function(id){return "/api/v1/users/self/bookmarks/" + id}, method: "PUT" },
  "BOOKMARKS_BOOKMARK_DELETE": { uri: function(id){return "/api/v1/users/self/bookmarks/" + id}, method: "DELETE" },
  "CALENDAR_EVENTS": { uri: function(){return "/api/v1/calendar_events"}, method: "GET" },
  "CALENDAR_EVENTS_USERS": { uri: function(user_id){return "/api/v1/users/" + user_id + "/calendar_events"}, method: "GET" },
  "CALENDAR_EVENTS_CREATE": { uri: function(){return "/api/v1/calendar_events"}, method: "POST" },
  "CALENDAR_EVENTS_GET": { uri: function(id){return "/api/v1/calendar_events/" + id}, method: "GET" },
  "CALENDAR_EVENTS_RESERVE": { uri: function(id){return "/api/v1/calendar_events/" + id + "/reservations"}, method: "POST" },
  "CALENDAR_EVENTS_RESERVE_BY_PARTICIPANT": { uri: function(id, participant_id){return "/api/v1/calendar_events/" + id + "/reservations/" + participant_id}, method: "POST" },
  "CALENDAR_EVENTS_UPDATE": { uri: function(id){return "/api/v1/calendar_events/" + id}, method: "PUT" },
  "CALENDAR_EVENTS_DELETE": { uri: function(id){return "/api/v1/calendar_events/" + id}, method: "DELETE" },
  "COLLABORATION_MEMBERS": { uri: function(id){return "/api/v1/collaborations/" + id + "/members"}, method: "GET" },
  "COMM_MESSAGES": { uri: function(){return "/api/v1/comm_messages"}, method: "GET" },
  "COMMUNICATION_CHANNELS": { uri: function(user_id){return "/api/v1/users/" + user_id + "/communication_channels"}, method: "GET" },
  "COMMUNICATION_CHANNEL_CREATE": { uri: function(user_id){return "/api/v1/users/" + user_id + "/communication_channels"}, method: "POST" },
  "COMMUNICATION_CHANNEL_DELETE": { uri: function(user_id, id){return "/api/v1/users/" + user_id + "/communication_channels/" + id}, method: "DELETE" },
  "COMMUNICATION_CHANNEL_DELETE_BY_TYPE_AND_ADDRESS": { uri: function(user_id, type, address){return "/api/v1/users/" + user_id + "/communication_channels/" + type + "/" + address}, method: "DELETE" },
  "CONFERENCES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/conferences"}, method: "GET" },
  "CONFERENCES_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/conferences"}, method: "GET" },
  "CONTENT_EXPORTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/content_exports"}, method: "GET" },
  "CONTENT_EXPORTS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/content_exports"}, method: "GET" },
  "CONTENT_EXPORTS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/content_exports"}, method: "GET" },
  "CONTENT_EXPORTS_GET": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/content_exports/" + id}, method: "GET" },
  "CONTENT_EXPORTS_GET_BY_GROUPS_AND_GROUP": { uri: function(group_id, id){return "/api/v1/groups/" + group_id + "/content_exports/" + id}, method: "GET" },
  "CONTENT_EXPORTS_GET_BY_USERS_AND_USER": { uri: function(user_id, id){return "/api/v1/users/" + user_id + "/content_exports/" + id}, method: "GET" },
  "CONTENT_EXPORTS_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/content_exports"}, method: "POST" },
  "CONTENT_EXPORTS_CREATE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/content_exports"}, method: "POST" },
  "CONTENT_EXPORTS_CREATE_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/content_exports"}, method: "POST" },
  "MIGRATION_ISSUES": { uri: function(account_id, content_migration_id){return "/api/v1/accounts/" + account_id + "/content_migrations/" + content_migration_id + "/migration_issues"}, method: "GET" },
  "MIGRATION_ISSUES_BY_COURSES_AND_COURSE": { uri: function(course_id, content_migration_id){return "/api/v1/courses/" + course_id + "/content_migrations/" + content_migration_id + "/migration_issues"}, method: "GET" },
  "MIGRATION_ISSUES_BY_GROUPS_AND_GROUP": { uri: function(group_id, content_migration_id){return "/api/v1/groups/" + group_id + "/content_migrations/" + content_migration_id + "/migration_issues"}, method: "GET" },
  "MIGRATION_ISSUES_BY_USERS_AND_USER": { uri: function(user_id, content_migration_id){return "/api/v1/users/" + user_id + "/content_migrations/" + content_migration_id + "/migration_issues"}, method: "GET" },
  "MIGRATION_ISSUE_GET": { uri: function(account_id, content_migration_id, id){return "/api/v1/accounts/" + account_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "GET" },
  "MIGRATION_ISSUE_GET_BY_COURSES_AND_COURSE": { uri: function(course_id, content_migration_id, id){return "/api/v1/courses/" + course_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "GET" },
  "MIGRATION_ISSUE_GET_BY_GROUPS_AND_GROUP": { uri: function(group_id, content_migration_id, id){return "/api/v1/groups/" + group_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "GET" },
  "MIGRATION_ISSUE_GET_BY_USERS_AND_USER": { uri: function(user_id, content_migration_id, id){return "/api/v1/users/" + user_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "GET" },
  "MIGRATION_ISSUE_UPDATE": { uri: function(account_id, content_migration_id, id){return "/api/v1/accounts/" + account_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "PUT" },
  "MIGRATION_ISSUE_UPDATE_BY_COURSES_AND_COURSE": { uri: function(course_id, content_migration_id, id){return "/api/v1/courses/" + course_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "PUT" },
  "MIGRATION_ISSUE_UPDATE_BY_GROUPS_AND_GROUP": { uri: function(group_id, content_migration_id, id){return "/api/v1/groups/" + group_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "PUT" },
  "MIGRATION_ISSUE_UPDATE_BY_USERS_AND_USER": { uri: function(user_id, content_migration_id, id){return "/api/v1/users/" + user_id + "/content_migrations/" + content_migration_id + "/migration_issues/" + id}, method: "PUT" },
  "CONTENT_MIGRATIONS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/content_migrations"}, method: "GET" },
  "CONTENT_MIGRATIONS_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/content_migrations"}, method: "GET" },
  "CONTENT_MIGRATIONS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/content_migrations"}, method: "GET" },
  "CONTENT_MIGRATIONS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/content_migrations"}, method: "GET" },
  "CONTENT_MIGRATION_GET": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/content_migrations/" + id}, method: "GET" },
  "CONTENT_MIGRATION_GET_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/content_migrations/" + id}, method: "GET" },
  "CONTENT_MIGRATION_GET_BY_GROUPS_AND_GROUP": { uri: function(group_id, id){return "/api/v1/groups/" + group_id + "/content_migrations/" + id}, method: "GET" },
  "CONTENT_MIGRATION_GET_BY_USERS_AND_USER": { uri: function(user_id, id){return "/api/v1/users/" + user_id + "/content_migrations/" + id}, method: "GET" },
  "CONTENT_MIGRATION_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/content_migrations"}, method: "POST" },
  "CONTENT_MIGRATION_CREATE_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/content_migrations"}, method: "POST" },
  "CONTENT_MIGRATION_CREATE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/content_migrations"}, method: "POST" },
  "CONTENT_MIGRATION_CREATE_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/content_migrations"}, method: "POST" },
  "CONTENT_MIGRATION_UPDATE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/content_migrations/" + id}, method: "PUT" },
  "CONTENT_MIGRATION_UPDATE_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/content_migrations/" + id}, method: "PUT" },
  "CONTENT_MIGRATION_UPDATE_BY_GROUPS_AND_GROUP": { uri: function(group_id, id){return "/api/v1/groups/" + group_id + "/content_migrations/" + id}, method: "PUT" },
  "CONTENT_MIGRATION_UPDATE_BY_USERS_AND_USER": { uri: function(user_id, id){return "/api/v1/users/" + user_id + "/content_migrations/" + id}, method: "PUT" },
  "CONTENT_MIGRATION_AVAILABLE_MIGRATORS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/content_migrations/migrators"}, method: "GET" },
  "CONTENT_MIGRATION_AVAILABLE_MIGRATORS_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/content_migrations/migrators"}, method: "GET" },
  "CONTENT_MIGRATION_AVAILABLE_MIGRATORS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/content_migrations/migrators"}, method: "GET" },
  "CONTENT_MIGRATION_AVAILABLE_MIGRATORS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/content_migrations/migrators"}, method: "GET" },
  "CONVERSATIONS": { uri: function(){return "/api/v1/conversations"}, method: "GET" },
  "CONVERSATION_CREATE": { uri: function(){return "/api/v1/conversations"}, method: "POST" },
  "CONVERSATION_BATCHES": { uri: function(){return "/api/v1/conversations/batches"}, method: "GET" },
  "CONVERSATION_GET": { uri: function(id){return "/api/v1/conversations/" + id}, method: "GET" },
  "CONVERSATION_UPDATE": { uri: function(id){return "/api/v1/conversations/" + id}, method: "PUT" },
  "CONVERSATION_MARK_ALL_AS_READ": { uri: function(){return "/api/v1/conversations/mark_all_as_read"}, method: "POST" },
  "CONVERSATION_DELETE": { uri: function(id){return "/api/v1/conversations/" + id}, method: "DELETE" },
  "CONVERSATION_ADD_RECIPIENTS": { uri: function(id){return "/api/v1/conversations/" + id + "/add_recipients"}, method: "POST" },
  "CONVERSATION_ADD_MESSAGE": { uri: function(id){return "/api/v1/conversations/" + id + "/add_message"}, method: "POST" },
  "CONVERSATION_REMOVE_MESSAGES": { uri: function(id){return "/api/v1/conversations/" + id + "/remove_messages"}, method: "POST" },
  "CONVERSATION_BATCH_UPDATE": { uri: function(){return "/api/v1/conversations"}, method: "PUT" },
  "CONVERSATION_FIND_RECIPIENTS": { uri: function(){return "/api/v1/conversations/find_recipients"}, method: "GET" },
  "CONVERSATION_UNREAD_COUNT": { uri: function(){return "/api/v1/conversations/unread_count"}, method: "GET" },
  "COURSE_AUDIT_FOR_COURSE": { uri: function(course_id){return "/api/v1/audit/course/courses/" + course_id}, method: "GET" },
  "QUIZZES_COURSE_QUIZ_EXTENSION_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/quiz_extensions"}, method: "POST" },
  "COURSES": { uri: function(){return "/api/v1/courses"}, method: "GET" },
  "COURSE_USERS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/users"}, method: "GET" },
  "COURSE_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/courses"}, method: "POST" },
  "COURSE_CREATE_FILE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/files"}, method: "POST" },
  "COURSE_STUDENTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/students"}, method: "GET" },
  "COURSE_USERS_BY_SEARCH_USERS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/search_users"}, method: "GET" },
  "COURSE_RECENT_STUDENTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/recent_students"}, method: "GET" },
  "COURSE_USER": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/users/" + id}, method: "GET" },
  "COURSE_PREVIEW_HTML": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/preview_html"}, method: "POST" },
  "COURSE_ACTIVITY_STREAM": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/activity_stream"}, method: "GET" },
  "COURSE_ACTIVITY_STREAM_SUMMARY": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/activity_stream/summary"}, method: "GET" },
  "COURSE_TODO_ITEMS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/todo"}, method: "GET" },
  "COURSE_DELETE": { uri: function(id){return "/api/v1/courses/" + id}, method: "DELETE" },
  "COURSE_SETTINGS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/settings"}, method: "GET" },
  "COURSE_UPDATE_SETTINGS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/settings"}, method: "PUT" },
  "COURSE_GET": { uri: function(id){return "/api/v1/courses/" + id}, method: "GET" },
  "COURSE_GET_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/courses/" + id}, method: "GET" },
  "COURSE_UPDATE": { uri: function(id){return "/api/v1/courses/" + id}, method: "PUT" },
  "COURSE_BATCH_UPDATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/courses"}, method: "PUT" },
  "COURSE_RESET_CONTENT": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/reset_content"}, method: "POST" },
  "CONTENT_IMPORT_COPY_COURSE_STATUS": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/course_copy/" + id}, method: "GET" },
  "CONTENT_IMPORT_COPY_COURSE_CONTENT": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/course_copy"}, method: "POST" },
  "CUSTOM_GRADEBOOK_COLUMNS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/custom_gradebook_columns"}, method: "GET" },
  "CUSTOM_GRADEBOOK_COLUMNS_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/custom_gradebook_columns"}, method: "POST" },
  "CUSTOM_GRADEBOOK_COLUMNS_UPDATE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/custom_gradebook_columns/" + id}, method: "PUT" },
  "CUSTOM_GRADEBOOK_COLUMNS_DELETE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/custom_gradebook_columns/" + id}, method: "DELETE" },
  "CUSTOM_GRADEBOOK_COLUMNS_REORDER": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/custom_gradebook_columns/reorder"}, method: "POST" },
  "CUSTOM_GRADEBOOK_COLUMN_DATA_S": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/custom_gradebook_columns/" + id + "/data"}, method: "GET" },
  "CUSTOM_GRADEBOOK_COLUMN_DATA_UPDATE": { uri: function(course_id, id, user_id){return "/api/v1/courses/" + course_id + "/custom_gradebook_columns/" + id + "/data/" + user_id}, method: "PUT" },
  "DISCUSSION_TOPICS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/discussion_topics"}, method: "GET" },
  "DISCUSSION_TOPICS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/discussion_topics"}, method: "GET" },
  "DISCUSSION_TOPIC_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/discussion_topics"}, method: "POST" },
  "DISCUSSION_TOPIC_CREATE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/discussion_topics"}, method: "POST" },
  "DISCUSSION_TOPIC_UPDATE": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id}, method: "PUT" },
  "DISCUSSION_TOPIC_UPDATE_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id}, method: "PUT" },
  "DISCUSSION_TOPIC_DELETE": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id}, method: "DELETE" },
  "DISCUSSION_TOPIC_DELETE_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id}, method: "DELETE" },
  "DISCUSSION_TOPIC_REORDER": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/discussion_topics/reorder"}, method: "POST" },
  "DISCUSSION_TOPIC_REORDER_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/discussion_topics/reorder"}, method: "POST" },
  "DISCUSSION_ENTRIE_UPDATE": { uri: function(course_id, topic_id, id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries/" + id}, method: "PUT" },
  "DISCUSSION_ENTRIE_UPDATE_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id, id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries/" + id}, method: "PUT" },
  "DISCUSSION_ENTRIE_DELETE": { uri: function(course_id, topic_id, id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries/" + id}, method: "DELETE" },
  "DISCUSSION_ENTRIE_DELETE_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id, id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries/" + id}, method: "DELETE" },
  "DISCUSSION_TOPICS_GET": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id}, method: "GET" },
  "DISCUSSION_TOPICS_GET_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id}, method: "GET" },
  "DISCUSSION_TOPICS_VIEW": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/view"}, method: "GET" },
  "DISCUSSION_TOPICS_VIEW_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/view"}, method: "GET" },
  "DISCUSSION_TOPICS_ADD_ENTRY": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries"}, method: "POST" },
  "DISCUSSION_TOPICS_ADD_ENTRY_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries"}, method: "POST" },
  "DISCUSSION_TOPICS_ENTRIES": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries"}, method: "GET" },
  "DISCUSSION_TOPICS_ENTRIES_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries"}, method: "GET" },
  "DISCUSSION_TOPICS_ADD_REPLY": { uri: function(course_id, topic_id, entry_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/replies"}, method: "POST" },
  "DISCUSSION_TOPICS_ADD_REPLY_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id, entry_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/replies"}, method: "POST" },
  "DISCUSSION_TOPICS_REPLIES": { uri: function(course_id, topic_id, entry_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/replies"}, method: "GET" },
  "DISCUSSION_TOPICS_REPLIES_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id, entry_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/replies"}, method: "GET" },
  "DISCUSSION_TOPICS_ENTRY_LIST": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entry_list"}, method: "GET" },
  "DISCUSSION_TOPICS_ENTRY_LIST_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entry_list"}, method: "GET" },
  "DISCUSSION_TOPICS_MARK_TOPIC_READ": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/read"}, method: "PUT" },
  "DISCUSSION_TOPICS_MARK_TOPIC_READ_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/read"}, method: "PUT" },
  "DISCUSSION_TOPICS_MARK_TOPIC_UNREAD": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/read"}, method: "DELETE" },
  "DISCUSSION_TOPICS_MARK_TOPIC_UNREAD_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/read"}, method: "DELETE" },
  "DISCUSSION_TOPICS_MARK_ALL_READ": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/read_all"}, method: "PUT" },
  "DISCUSSION_TOPICS_MARK_ALL_READ_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/read_all"}, method: "PUT" },
  "DISCUSSION_TOPICS_MARK_ALL_UNREAD": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/read_all"}, method: "DELETE" },
  "DISCUSSION_TOPICS_MARK_ALL_UNREAD_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/read_all"}, method: "DELETE" },
  "DISCUSSION_TOPICS_MARK_ENTRY_READ": { uri: function(course_id, topic_id, entry_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/read"}, method: "PUT" },
  "DISCUSSION_TOPICS_MARK_ENTRY_READ_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id, entry_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/read"}, method: "PUT" },
  "DISCUSSION_TOPICS_MARK_ENTRY_UNREAD": { uri: function(course_id, topic_id, entry_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/read"}, method: "DELETE" },
  "DISCUSSION_TOPICS_MARK_ENTRY_UNREAD_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id, entry_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/read"}, method: "DELETE" },
  "DISCUSSION_TOPICS_RATE_ENTRY": { uri: function(course_id, topic_id, entry_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/rating"}, method: "POST" },
  "DISCUSSION_TOPICS_RATE_ENTRY_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id, entry_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/entries/" + entry_id + "/rating"}, method: "POST" },
  "DISCUSSION_TOPICSUBSCRIBE_TOPIC": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/subscribed"}, method: "PUT" },
  "DISCUSSION_TOPICSUBSCRIBE_TOPIC_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/subscribed"}, method: "PUT" },
  "DISCUSSION_TOPICS_UNSUBSCRIBE_TOPIC": { uri: function(course_id, topic_id){return "/api/v1/courses/" + course_id + "/discussion_topics/" + topic_id + "/subscribed"}, method: "DELETE" },
  "DISCUSSION_TOPICS_UNSUBSCRIBE_TOPIC_BY_GROUPS_AND_GROUP": { uri: function(group_id, topic_id){return "/api/v1/groups/" + group_id + "/discussion_topics/" + topic_id + "/subscribed"}, method: "DELETE" },
  "TERM_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/terms"}, method: "POST" },
  "TERM_UPDATE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/terms/" + id}, method: "PUT" },
  "TERM_DELETE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/terms/" + id}, method: "DELETE" },
  "TERMS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/terms"}, method: "GET" },
  "ENROLLMENTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/enrollments"}, method: "GET" },
  "ENROLLMENTS_BY_SECTIONS_AND_SECTION": { uri: function(section_id){return "/api/v1/sections/" + section_id + "/enrollments"}, method: "GET" },
  "ENROLLMENTS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/enrollments"}, method: "GET" },
  "ENROLLMENTS_GET": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/enrollments/" + id}, method: "GET" },
  "ENROLLMENTS_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/enrollments"}, method: "POST" },
  "ENROLLMENTS_CREATE_BY_SECTIONS_AND_SECTION": { uri: function(section_id){return "/api/v1/sections/" + section_id + "/enrollments"}, method: "POST" },
  "ENROLLMENTS_DELETE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/enrollments/" + id}, method: "DELETE" },
  "ENROLLMENTS_REACTIVATE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/enrollments/" + id + "/reactivate"}, method: "PUT" },
  "ERROR_CREATE": { uri: function(){return "/api/v1/error_reports"}, method: "POST" },
  "EXTERNAL_TOOLS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/external_tools"}, method: "GET" },
  "EXTERNAL_TOOLS_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/external_tools"}, method: "GET" },
  "EXTERNAL_TOOL_GENERATE_SESSIONLESS_LAUNCH": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/external_tools/sessionless_launch"}, method: "GET" },
  "EXTERNAL_TOOL_GENERATE_SESSIONLESS_LAUNCH_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/external_tools/sessionless_launch"}, method: "GET" },
  "EXTERNAL_TOOL_GET": { uri: function(course_id, external_tool_id){return "/api/v1/courses/" + course_id + "/external_tools/" + external_tool_id}, method: "GET" },
  "EXTERNAL_TOOL_GET_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, external_tool_id){return "/api/v1/accounts/" + account_id + "/external_tools/" + external_tool_id}, method: "GET" },
  "EXTERNAL_TOOL_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/external_tools"}, method: "POST" },
  "EXTERNAL_TOOL_CREATE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/external_tools"}, method: "POST" },
  "EXTERNAL_TOOL_UPDATE": { uri: function(course_id, external_tool_id){return "/api/v1/courses/" + course_id + "/external_tools/" + external_tool_id}, method: "PUT" },
  "EXTERNAL_TOOL_UPDATE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, external_tool_id){return "/api/v1/accounts/" + account_id + "/external_tools/" + external_tool_id}, method: "PUT" },
  "EXTERNAL_TOOL_DELETE": { uri: function(course_id, external_tool_id){return "/api/v1/courses/" + course_id + "/external_tools/" + external_tool_id}, method: "DELETE" },
  "EXTERNAL_TOOL_DELETE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, external_tool_id){return "/api/v1/accounts/" + account_id + "/external_tools/" + external_tool_id}, method: "DELETE" },
  "FAVORITE_LIST_FAVORITE_COURSES": { uri: function(){return "/api/v1/users/self/favorites/courses"}, method: "GET" },
  "FAVORITE_LIST_FAVORITE_GROUPS": { uri: function(){return "/api/v1/users/self/favorites/groups"}, method: "GET" },
  "FAVORITE_ADD_FAVORITE_COURSE": { uri: function(id){return "/api/v1/users/self/favorites/courses/" + id}, method: "POST" },
  "FAVORITE_ADD_FAVORITE_GROUPS": { uri: function(id){return "/api/v1/users/self/favorites/groups/" + id}, method: "POST" },
  "FAVORITE_REMOVE_FAVORITE_COURSE": { uri: function(id){return "/api/v1/users/self/favorites/courses/" + id}, method: "DELETE" },
  "FAVORITE_REMOVE_FAVORITE_GROUPS": { uri: function(id){return "/api/v1/users/self/favorites/groups/" + id}, method: "DELETE" },
  "FAVORITE_RESET_COURSE_FAVORITES": { uri: function(){return "/api/v1/users/self/favorites/courses"}, method: "DELETE" },
  "FAVORITE_RESET_GROUPS_FAVORITES": { uri: function(){return "/api/v1/users/self/favorites/groups"}, method: "DELETE" },
  "FEATURE_FLAGS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/features"}, method: "GET" },
  "FEATURE_FLAGS_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/features"}, method: "GET" },
  "FEATURE_FLAGS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/features"}, method: "GET" },
  "FEATURE_FLAG_ENABLED_FEATURES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/features/enabled"}, method: "GET" },
  "FEATURE_FLAG_ENABLED_FEATURES_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/features/enabled"}, method: "GET" },
  "FEATURE_FLAG_ENABLED_FEATURES_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/features/enabled"}, method: "GET" },
  "FEATURE_FLAG_GET": { uri: function(course_id, feature){return "/api/v1/courses/" + course_id + "/features/flags/" + feature}, method: "GET" },
  "FEATURE_FLAG_GET_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, feature){return "/api/v1/accounts/" + account_id + "/features/flags/" + feature}, method: "GET" },
  "FEATURE_FLAG_GET_BY_USERS_AND_USER": { uri: function(user_id, feature){return "/api/v1/users/" + user_id + "/features/flags/" + feature}, method: "GET" },
  "FEATURE_FLAG_UPDATE": { uri: function(course_id, feature){return "/api/v1/courses/" + course_id + "/features/flags/" + feature}, method: "PUT" },
  "FEATURE_FLAG_UPDATE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, feature){return "/api/v1/accounts/" + account_id + "/features/flags/" + feature}, method: "PUT" },
  "FEATURE_FLAG_UPDATE_BY_USERS_AND_USER": { uri: function(user_id, feature){return "/api/v1/users/" + user_id + "/features/flags/" + feature}, method: "PUT" },
  "FEATURE_FLAG_DELETE": { uri: function(course_id, feature){return "/api/v1/courses/" + course_id + "/features/flags/" + feature}, method: "DELETE" },
  "FEATURE_FLAG_DELETE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, feature){return "/api/v1/accounts/" + account_id + "/features/flags/" + feature}, method: "DELETE" },
  "FEATURE_FLAG_DELETE_BY_USERS_AND_USER": { uri: function(user_id, feature){return "/api/v1/users/" + user_id + "/features/flags/" + feature}, method: "DELETE" },
  "FILE_QUOTA": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/files/quota"}, method: "GET" },
  "FILE_QUOTA_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/files/quota"}, method: "GET" },
  "FILE_QUOTA_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/files/quota"}, method: "GET" },
  "FILES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/files"}, method: "GET" },
  "FILES_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/files"}, method: "GET" },
  "FILES_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/files"}, method: "GET" },
  "FILES_BY_FOLDERS_AND_ID": { uri: function(id){return "/api/v1/folders/" + id + "/files"}, method: "GET" },
  "FILE_PUBLIC_URL": { uri: function(id){return "/api/v1/files/" + id + "/public_url"}, method: "GET" },
  "FILE_SHOW": { uri: function(id){return "/api/v1/files/" + id}, method: "GET" },
  "FILE_SHOW_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/files/" + id}, method: "GET" },
  "FILE_SHOW_BY_GROUPS_AND_GROUP": { uri: function(group_id, id){return "/api/v1/groups/" + group_id + "/files/" + id}, method: "GET" },
  "FILE_SHOW_BY_USERS_AND_USER": { uri: function(user_id, id){return "/api/v1/users/" + user_id + "/files/" + id}, method: "GET" },
  "FILE_UPDATE": { uri: function(id){return "/api/v1/files/" + id}, method: "PUT" },
  "FILE_DELETE": { uri: function(id){return "/api/v1/files/" + id}, method: "DELETE" },
  "FOLDERS": { uri: function(id){return "/api/v1/folders/" + id + "/folders"}, method: "GET" },
  "FOLDER_LIST_ALL_FOLDERS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/folders"}, method: "GET" },
  "FOLDER_LIST_ALL_FOLDERS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/folders"}, method: "GET" },
  "FOLDER_LIST_ALL_FOLDERS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/folders"}, method: "GET" },
  "FOLDER_RESOLVE_PATH": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/folders/by_path"}, method: "GET" },
  "FOLDER_RESOLVE_PATH_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/folders/by_path"}, method: "GET" },
  "FOLDER_RESOLVE_PATH_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/folders/by_path"}, method: "GET" },
  "FOLDER_GET": { uri: function(id){return "/api/v1/folders/" + id}, method: "GET" },
  "FOLDER_GET_BY_USERS_AND_USER": { uri: function(user_id, id){return "/api/v1/users/" + user_id + "/folders/" + id}, method: "GET" },
  "FOLDER_GET_BY_GROUPS_AND_GROUP": { uri: function(group_id, id){return "/api/v1/groups/" + group_id + "/folders/" + id}, method: "GET" },
  "FOLDER_UPDATE": { uri: function(id){return "/api/v1/folders/" + id}, method: "PUT" },
  "FOLDER_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/folders"}, method: "POST" },
  "FOLDER_CREATE_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/folders"}, method: "POST" },
  "FOLDER_CREATE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/folders"}, method: "POST" },
  "FOLDER_CREATE_BY_FOLDER": { uri: function(folder_id){return "/api/v1/folders/" + folder_id + "/folders"}, method: "POST" },
  "FOLDER_DESTROY": { uri: function(id){return "/api/v1/folders/" + id}, method: "DELETE" },
  "FOLDER_CREATE_FILE": { uri: function(folder_id){return "/api/v1/folders/" + folder_id + "/files"}, method: "POST" },
  "FOLDER_COPY_FILE": { uri: function(dest_folder_id){return "/api/v1/folders/" + dest_folder_id + "/copy_file"}, method: "POST" },
  "FOLDER_COPY_FOLDER": { uri: function(dest_folder_id){return "/api/v1/folders/" + dest_folder_id + "/copy_folder"}, method: "POST" },
  "USAGE_RIGHT_SET_USAGE_RIGHTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/usage_rights"}, method: "PUT" },
  "USAGE_RIGHT_SET_USAGE_RIGHTS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/usage_rights"}, method: "PUT" },
  "USAGE_RIGHT_SET_USAGE_RIGHTS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/usage_rights"}, method: "PUT" },
  "USAGE_RIGHT_REMOVE_USAGE_RIGHTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/usage_rights"}, method: "DELETE" },
  "USAGE_RIGHT_REMOVE_USAGE_RIGHTS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/usage_rights"}, method: "DELETE" },
  "USAGE_RIGHT_REMOVE_USAGE_RIGHTS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/usage_rights"}, method: "DELETE" },
  "USAGE_RIGHT_LICENSES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/content_licenses"}, method: "GET" },
  "USAGE_RIGHT_LICENSES_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/content_licenses"}, method: "GET" },
  "USAGE_RIGHT_LICENSES_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/content_licenses"}, method: "GET" },
  "GRADE_CHANGE_AUDIT_FOR_ASSIGNMENT": { uri: function(assignment_id){return "/api/v1/audit/grade_change/assignments/" + assignment_id}, method: "GET" },
  "GRADE_CHANGE_AUDIT_FOR_COURSE": { uri: function(course_id){return "/api/v1/audit/grade_change/courses/" + course_id}, method: "GET" },
  "GRADE_CHANGE_AUDIT_FOR_STUDENT": { uri: function(student_id){return "/api/v1/audit/grade_change/students/" + student_id}, method: "GET" },
  "GRADE_CHANGE_AUDIT_FOR_GRADER": { uri: function(grader_id){return "/api/v1/audit/grade_change/graders/" + grader_id}, method: "GET" },
  "GRADEBOOK_HISTORY_DAYS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/gradebook_history/days"}, method: "GET" },
  "GRADEBOOK_HISTORY_DAY_DETAILS": { uri: function(course_id, date){return "/api/v1/courses/" + course_id + "/gradebook_history/" + date}, method: "GET" },
  "GRADEBOOK_HISTORY_SUBMISSIONS": { uri: function(course_id, date, grader_id, assignment_id){return "/api/v1/courses/" + course_id + "/gradebook_history/" + date + "/graders/" + grader_id + "/assignments/" + assignment_id + "/submissions"}, method: "GET" },
  "GRADEBOOK_HISTORY_FEED": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/gradebook_history/feed"}, method: "GET" },
  "GRADING_PERIODS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/grading_periods"}, method: "GET" },
  "GRADING_PERIODS_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/grading_periods"}, method: "GET" },
  "GRADING_PERIOD_GET": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/grading_periods/" + id}, method: "GET" },
  "GRADING_PERIOD_GET_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/grading_periods/" + id}, method: "GET" },
  "GRADING_PERIOD_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/grading_periods"}, method: "POST" },
  "GRADING_PERIOD_CREATE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/grading_periods"}, method: "POST" },
  "GRADING_PERIOD_UPDATE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/grading_periods/" + id}, method: "PUT" },
  "GRADING_PERIOD_UPDATE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/grading_periods/" + id}, method: "PUT" },
  "GRADING_PERIOD_DELETE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/grading_periods/" + id}, method: "DELETE" },
  "GRADING_PERIOD_DELETE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/grading_periods/" + id}, method: "DELETE" },
  "GRADING_STANDARDS_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/grading_standards"}, method: "POST" },
  "GRADING_STANDARDS_CREATE_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/grading_standards"}, method: "POST" },
  "GRADING_STANDARDS_CONTEXTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/grading_standards"}, method: "GET" },
  "GRADING_STANDARDS_CONTEXTS_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/grading_standards"}, method: "GET" },
  "GROUP_CATEGORIES": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/group_categories"}, method: "GET" },
  "GROUP_CATEGORIES_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/group_categories"}, method: "GET" },
  "GROUP_CATEGORIE_GET": { uri: function(group_category_id){return "/api/v1/group_categories/" + group_category_id}, method: "GET" },
  "GROUP_CATEGORIE_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/group_categories"}, method: "POST" },
  "GROUP_CATEGORIE_CREATE_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/group_categories"}, method: "POST" },
  "GROUP_CATEGORIE_UPDATE": { uri: function(group_category_id){return "/api/v1/group_categories/" + group_category_id}, method: "PUT" },
  "GROUP_CATEGORIE_DELETE": { uri: function(group_category_id){return "/api/v1/group_categories/" + group_category_id}, method: "DELETE" },
  "GROUP_CATEGORIE_GROUPS": { uri: function(group_category_id){return "/api/v1/group_categories/" + group_category_id + "/groups"}, method: "GET" },
  "GROUP_CATEGORIE_USERS": { uri: function(group_category_id){return "/api/v1/group_categories/" + group_category_id + "/users"}, method: "GET" },
  "GROUP_CATEGORIE_ASSIGN_UNASSIGNED_MEMBERS": { uri: function(group_category_id){return "/api/v1/group_categories/" + group_category_id + "/assign_unassigned_members"}, method: "POST" },
  "GROUPS": { uri: function(){return "/api/v1/users/self/groups"}, method: "GET" },
  "GROUP_CONTEXTS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/groups"}, method: "GET" },
  "GROUP_CONTEXTS_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/groups"}, method: "GET" },
  "GROUP_GET": { uri: function(group_id){return "/api/v1/groups/" + group_id}, method: "GET" },
  "GROUP_CREATE": { uri: function(){return "/api/v1/groups"}, method: "POST" },
  "GROUP_CREATE_BY_GROUP_CATEGORIES_AND_GROUP_CATEGORY": { uri: function(group_category_id){return "/api/v1/group_categories/" + group_category_id + "/groups"}, method: "POST" },
  "GROUP_UPDATE": { uri: function(group_id){return "/api/v1/groups/" + group_id}, method: "PUT" },
  "GROUP_DELETE": { uri: function(group_id){return "/api/v1/groups/" + group_id}, method: "DELETE" },
  "GROUP_INVITE": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/invite"}, method: "POST" },
  "GROUP_USERS": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/users"}, method: "GET" },
  "GROUP_CREATE_FILE": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/files"}, method: "POST" },
  "GROUP_PREVIEW_HTML": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/preview_html"}, method: "POST" },
  "GROUP_ACTIVITY_STREAM": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/activity_stream"}, method: "GET" },
  "GROUP_ACTIVITY_STREAM_SUMMARY": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/activity_stream/summary"}, method: "GET" },
  "GROUP_MEMBERSHIPS": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/memberships"}, method: "GET" },
  "GROUP_MEMBERSHIP_GET": { uri: function(group_id, membership_id){return "/api/v1/groups/" + group_id + "/memberships/" + membership_id}, method: "GET" },
  "GROUP_MEMBERSHIP_GET_BY_USERS_AND_USER": { uri: function(group_id, user_id){return "/api/v1/groups/" + group_id + "/users/" + user_id}, method: "GET" },
  "GROUP_MEMBERSHIP_CREATE": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/memberships"}, method: "POST" },
  "GROUP_MEMBERSHIP_UPDATE": { uri: function(group_id, membership_id){return "/api/v1/groups/" + group_id + "/memberships/" + membership_id}, method: "PUT" },
  "GROUP_MEMBERSHIP_UPDATE_BY_USERS_AND_USER": { uri: function(group_id, user_id){return "/api/v1/groups/" + group_id + "/users/" + user_id}, method: "PUT" },
  "GROUP_MEMBERSHIP_DELETE": { uri: function(group_id, membership_id){return "/api/v1/groups/" + group_id + "/memberships/" + membership_id}, method: "DELETE" },
  "GROUP_MEMBERSHIP_DELETE_BY_USERS_AND_USER": { uri: function(group_id, user_id){return "/api/v1/groups/" + group_id + "/users/" + user_id}, method: "DELETE" },
  "JWT_CREATE": { uri: function(){return "/api/v1/jwts"}, method: "POST" },
  "LIVE_ASSESSMENTS_RESULT_CREATE": { uri: function(course_id, assessment_id){return "/api/v1/courses/" + course_id + "/live_assessments/" + assessment_id + "/results"}, method: "POST" },
  "LIVE_ASSESSMENTS_RESULTS": { uri: function(course_id, assessment_id){return "/api/v1/courses/" + course_id + "/live_assessments/" + assessment_id + "/results"}, method: "GET" },
  "LIVE_ASSESSMENTS_ASSESSMENT_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/live_assessments"}, method: "POST" },
  "LIVE_ASSESSMENTS_ASSESSMENTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/live_assessments"}, method: "GET" },
  "PSEUDONYMS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/logins"}, method: "GET" },
  "PSEUDONYMS_BY_USERS_AND_USER": { uri: function(user_id){return "/api/v1/users/" + user_id + "/logins"}, method: "GET" },
  "PSEUDONYM_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/logins"}, method: "POST" },
  "PSEUDONYM_UPDATE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/logins/" + id}, method: "PUT" },
  "PSEUDONYM_DELETE": { uri: function(user_id, id){return "/api/v1/users/" + user_id + "/logins/" + id}, method: "DELETE" },
  "MODERATION_SET_S": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/moderated_students"}, method: "GET" },
  "MODERATION_SET_CREATE": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/moderated_students"}, method: "POST" },
  "PROVISIONAL_GRADE_STATUS": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/provisional_grades/status"}, method: "GET" },
  "PROVISIONAL_GRADE_SELECT": { uri: function(course_id, assignment_id, provisional_grade_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/provisional_grades/" + provisional_grade_id + "/select"}, method: "PUT" },
  "PROVISIONAL_GRADE_COPY_TO_FINAL_MARK": { uri: function(course_id, assignment_id, provisional_grade_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/provisional_grades/" + provisional_grade_id + "/copy_to_final_mark"}, method: "POST" },
  "PROVISIONAL_GRADE_PUBLISH": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/provisional_grades/publish"}, method: "POST" },
  "CONTEXT_MODULES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/modules"}, method: "GET" },
  "CONTEXT_MODULES_GET": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/modules/" + id}, method: "GET" },
  "CONTEXT_MODULES_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/modules"}, method: "POST" },
  "CONTEXT_MODULES_UPDATE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/modules/" + id}, method: "PUT" },
  "CONTEXT_MODULES_DELETE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/modules/" + id}, method: "DELETE" },
  "CONTEXT_MODULES_RELOCK": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/modules/" + id + "/relock"}, method: "PUT" },
  "CONTEXT_MODULE_ITEMS": { uri: function(course_id, module_id){return "/api/v1/courses/" + course_id + "/modules/" + module_id + "/items"}, method: "GET" },
  "CONTEXT_MODULE_ITEMS_GET": { uri: function(course_id, module_id, id){return "/api/v1/courses/" + course_id + "/modules/" + module_id + "/items/" + id}, method: "GET" },
  "CONTEXT_MODULE_ITEMS_CREATE": { uri: function(course_id, module_id){return "/api/v1/courses/" + course_id + "/modules/" + module_id + "/items"}, method: "POST" },
  "CONTEXT_MODULE_ITEMS_UPDATE": { uri: function(course_id, module_id, id){return "/api/v1/courses/" + course_id + "/modules/" + module_id + "/items/" + id}, method: "PUT" },
  "CONTEXT_MODULE_ITEMS_DELETE": { uri: function(course_id, module_id, id){return "/api/v1/courses/" + course_id + "/modules/" + module_id + "/items/" + id}, method: "DELETE" },
  "CONTEXT_MODULE_ITEMS_MARK_AS_DONE": { uri: function(course_id, module_id, id){return "/api/v1/courses/" + course_id + "/modules/" + module_id + "/items/" + id + "/done"}, method: "PUT" },
  "CONTEXT_MODULE_ITEMS_ITEM_SEQUENCE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/module_item_sequence"}, method: "GET" },
  "CONTEXT_MODULE_ITEMS_MARK_ITEM_READ": { uri: function(course_id, module_id, id){return "/api/v1/courses/" + course_id + "/modules/" + module_id + "/items/" + id + "/mark_read"}, method: "POST" },
  "NOTIFICATION_PREFERENCES": { uri: function(user_id, communication_channel_id){return "/api/v1/users/" + user_id + "/communication_channels/" + communication_channel_id + "/notification_preferences"}, method: "GET" },
  "NOTIFICATION_PREFERENCES_BY_TYPE_AND_ADDRESS": { uri: function(user_id, type, address){return "/api/v1/users/" + user_id + "/communication_channels/" + type + "/" + address + "/notification_preferences"}, method: "GET" },
  "NOTIFICATION_PREFERENCE_CATEGORYS": { uri: function(user_id, communication_channel_id){return "/api/v1/users/" + user_id + "/communication_channels/" + communication_channel_id + "/notification_preference_categories"}, method: "GET" },
  "NOTIFICATION_PREFERENCE_GET": { uri: function(user_id, communication_channel_id, notification){return "/api/v1/users/" + user_id + "/communication_channels/" + communication_channel_id + "/notification_preferences/" + notification}, method: "GET" },
  "NOTIFICATION_PREFERENCE_GET_BY_TYPE_AND_ADDRESS": { uri: function(user_id, type, address, notification){return "/api/v1/users/" + user_id + "/communication_channels/" + type + "/" + address + "/notification_preferences/" + notification}, method: "GET" },
  "NOTIFICATION_PREFERENCE_UPDATE": { uri: function(communication_channel_id, notification){return "/api/v1/users/self/communication_channels/" + communication_channel_id + "/notification_preferences/" + notification}, method: "PUT" },
  "NOTIFICATION_PREFERENCE_UPDATE_BY_TYPE_AND_ADDRESS": { uri: function(type, address, notification){return "/api/v1/users/self/communication_channels/" + type + "/" + address + "/notification_preferences/" + notification}, method: "PUT" },
  "NOTIFICATION_PREFERENCE_UPDATE_PREFERENCES_BY_CATEGORY": { uri: function(communication_channel_id, category){return "/api/v1/users/self/communication_channels/" + communication_channel_id + "/notification_preference_categories/" + category}, method: "PUT" },
  "NOTIFICATION_PREFERENCE_UPDATE_ALL": { uri: function(communication_channel_id){return "/api/v1/users/self/communication_channels/" + communication_channel_id + "/notification_preferences"}, method: "PUT" },
  "NOTIFICATION_PREFERENCE_UPDATE_ALL_BY_TYPE_AND_ADDRESS": { uri: function(type, address){return "/api/v1/users/self/communication_channels/" + type + "/" + address + "/notification_preferences"}, method: "PUT" },
  "OUTCOME_GROUPS_REDIRECT": { uri: function(){return "/api/v1/global/root_outcome_group"}, method: "GET" },
  "OUTCOME_GROUPS_REDIRECT_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/root_outcome_group"}, method: "GET" },
  "OUTCOME_GROUPS_REDIRECT_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/root_outcome_group"}, method: "GET" },
  "OUTCOME_GROUPS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/outcome_groups"}, method: "GET" },
  "OUTCOME_GROUPS_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/outcome_groups"}, method: "GET" },
  "OUTCOME_GROUPS_LINKS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/outcome_group_links"}, method: "GET" },
  "OUTCOME_GROUPS_LINKS_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/outcome_group_links"}, method: "GET" },
  "OUTCOME_GROUPS_GET": { uri: function(id){return "/api/v1/global/outcome_groups/" + id}, method: "GET" },
  "OUTCOME_GROUPS_GET_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id}, method: "GET" },
  "OUTCOME_GROUPS_GET_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id}, method: "GET" },
  "OUTCOME_GROUPS_UPDATE": { uri: function(id){return "/api/v1/global/outcome_groups/" + id}, method: "PUT" },
  "OUTCOME_GROUPS_UPDATE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id}, method: "PUT" },
  "OUTCOME_GROUPS_UPDATE_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id}, method: "PUT" },
  "OUTCOME_GROUPS_DELETE": { uri: function(id){return "/api/v1/global/outcome_groups/" + id}, method: "DELETE" },
  "OUTCOME_GROUPS_DELETE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id}, method: "DELETE" },
  "OUTCOME_GROUPS_DELETE_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id}, method: "DELETE" },
  "OUTCOME_GROUPS_OUTCOMES": { uri: function(id){return "/api/v1/global/outcome_groups/" + id + "/outcomes"}, method: "GET" },
  "OUTCOME_GROUPS_OUTCOMES_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id + "/outcomes"}, method: "GET" },
  "OUTCOME_GROUPS_OUTCOMES_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id + "/outcomes"}, method: "GET" },
  "OUTCOME_GROUPS_LINK": { uri: function(id){return "/api/v1/global/outcome_groups/" + id + "/outcomes"}, method: "POST" },
  "OUTCOME_GROUPS_LINK_BY_OUTCOME": { uri: function(id, outcome_id){return "/api/v1/global/outcome_groups/" + id + "/outcomes/" + outcome_id}, method: "PUT" },
  "OUTCOME_GROUPS_LINK_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id + "/outcomes"}, method: "POST" },
  "OUTCOME_GROUPS_LINK_BY_ACCOUNTS_AND_ACCOUNT_AND_OUTCOME": { uri: function(account_id, id, outcome_id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id + "/outcomes/" + outcome_id}, method: "PUT" },
  "OUTCOME_GROUPS_LINK_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id + "/outcomes"}, method: "POST" },
  "OUTCOME_GROUPS_LINK_BY_COURSES_AND_COURSE_AND_OUTCOME": { uri: function(course_id, id, outcome_id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id + "/outcomes/" + outcome_id}, method: "PUT" },
  "OUTCOME_GROUPS_UNLINK": { uri: function(id, outcome_id){return "/api/v1/global/outcome_groups/" + id + "/outcomes/" + outcome_id}, method: "DELETE" },
  "OUTCOME_GROUPS_UNLINK_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id, outcome_id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id + "/outcomes/" + outcome_id}, method: "DELETE" },
  "OUTCOME_GROUPS_UNLINK_BY_COURSES_AND_COURSE": { uri: function(course_id, id, outcome_id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id + "/outcomes/" + outcome_id}, method: "DELETE" },
  "OUTCOME_GROUPSUBGROUPS": { uri: function(id){return "/api/v1/global/outcome_groups/" + id + "/subgroups"}, method: "GET" },
  "OUTCOME_GROUPSUBGROUPS_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id + "/subgroups"}, method: "GET" },
  "OUTCOME_GROUPSUBGROUPS_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id + "/subgroups"}, method: "GET" },
  "OUTCOME_GROUPS_CREATE": { uri: function(id){return "/api/v1/global/outcome_groups/" + id + "/subgroups"}, method: "POST" },
  "OUTCOME_GROUPS_CREATE_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id + "/subgroups"}, method: "POST" },
  "OUTCOME_GROUPS_CREATE_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id + "/subgroups"}, method: "POST" },
  "OUTCOME_GROUPS_IMPORT": { uri: function(id){return "/api/v1/global/outcome_groups/" + id + "/import"}, method: "POST" },
  "OUTCOME_GROUPS_IMPORT_BY_ACCOUNTS_AND_ACCOUNT": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/outcome_groups/" + id + "/import"}, method: "POST" },
  "OUTCOME_GROUPS_IMPORT_BY_COURSES_AND_COURSE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/outcome_groups/" + id + "/import"}, method: "POST" },
  "OUTCOME_RESULTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/outcome_results"}, method: "GET" },
  "OUTCOME_RESULT_ROLLUPS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/outcome_rollups"}, method: "GET" },
  "OUTCOMES_GET": { uri: function(id){return "/api/v1/outcomes/" + id}, method: "GET" },
  "OUTCOMES_UPDATE": { uri: function(id){return "/api/v1/outcomes/" + id}, method: "PUT" },
  "WIKI_PAGES_GET_FRONT_PAGE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/front_page"}, method: "GET" },
  "WIKI_PAGES_GET_FRONT_PAGE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/front_page"}, method: "GET" },
  "WIKI_PAGES_UPDATE_FRONT_PAGE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/front_page"}, method: "PUT" },
  "WIKI_PAGES_UPDATE_FRONT_PAGE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/front_page"}, method: "PUT" },
  "WIKI_PAGES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/pages"}, method: "GET" },
  "WIKI_PAGES_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/pages"}, method: "GET" },
  "WIKI_PAGES_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/pages"}, method: "POST" },
  "WIKI_PAGES_CREATE_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/pages"}, method: "POST" },
  "WIKI_PAGES_GET": { uri: function(course_id, url){return "/api/v1/courses/" + course_id + "/pages/" + url}, method: "GET" },
  "WIKI_PAGES_GET_BY_GROUPS_AND_GROUP": { uri: function(group_id, url){return "/api/v1/groups/" + group_id + "/pages/" + url}, method: "GET" },
  "WIKI_PAGES_UPDATE": { uri: function(course_id, url){return "/api/v1/courses/" + course_id + "/pages/" + url}, method: "PUT" },
  "WIKI_PAGES_UPDATE_BY_GROUPS_AND_GROUP": { uri: function(group_id, url){return "/api/v1/groups/" + group_id + "/pages/" + url}, method: "PUT" },
  "WIKI_PAGES_DELETE": { uri: function(course_id, url){return "/api/v1/courses/" + course_id + "/pages/" + url}, method: "DELETE" },
  "WIKI_PAGES_DELETE_BY_GROUPS_AND_GROUP": { uri: function(group_id, url){return "/api/v1/groups/" + group_id + "/pages/" + url}, method: "DELETE" },
  "WIKI_PAGES_REVISIONS": { uri: function(course_id, url){return "/api/v1/courses/" + course_id + "/pages/" + url + "/revisions"}, method: "GET" },
  "WIKI_PAGES_REVISIONS_BY_GROUPS_AND_GROUP": { uri: function(group_id, url){return "/api/v1/groups/" + group_id + "/pages/" + url + "/revisions"}, method: "GET" },
  "WIKI_PAGES_GET_REVISION": { uri: function(course_id, url){return "/api/v1/courses/" + course_id + "/pages/" + url + "/revisions/latest"}, method: "GET" },
  "WIKI_PAGES_GET_REVISION_BY_GROUPS_AND_GROUP": { uri: function(group_id, url){return "/api/v1/groups/" + group_id + "/pages/" + url + "/revisions/latest"}, method: "GET" },
  "WIKI_PAGES_GET_REVISION_BY_REVISION": { uri: function(course_id, url, revision_id){return "/api/v1/courses/" + course_id + "/pages/" + url + "/revisions/" + revision_id}, method: "GET" },
  "WIKI_PAGES_GET_REVISION_BY_GROUPS_AND_GROUP_AND_REVISION": { uri: function(group_id, url, revision_id){return "/api/v1/groups/" + group_id + "/pages/" + url + "/revisions/" + revision_id}, method: "GET" },
  "WIKI_PAGES_REVERT": { uri: function(course_id, url, revision_id){return "/api/v1/courses/" + course_id + "/pages/" + url + "/revisions/" + revision_id}, method: "POST" },
  "WIKI_PAGES_REVERT_BY_GROUPS_AND_GROUP": { uri: function(group_id, url, revision_id){return "/api/v1/groups/" + group_id + "/pages/" + url + "/revisions/" + revision_id}, method: "POST" },
  "PEER_REVIEWS": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/peer_reviews"}, method: "GET" },
  "PEER_REVIEWS_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/peer_reviews"}, method: "GET" },
  "PEER_REVIEWS_BY_SUBMISSIONS_AND_SUBMISSION": { uri: function(course_id, assignment_id, submission_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + submission_id + "/peer_reviews"}, method: "GET" },
  "PEER_REVIEWS_BY_SECTIONS_AND_SECTION_AND_SUBMISSIONS_AND_SUBMISSION": { uri: function(section_id, assignment_id, submission_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + submission_id + "/peer_reviews"}, method: "GET" },
  "PEER_REVIEWS_CREATE": { uri: function(course_id, assignment_id, submission_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + submission_id + "/peer_reviews"}, method: "POST" },
  "PEER_REVIEWS_CREATE_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id, submission_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + submission_id + "/peer_reviews"}, method: "POST" },
  "PEER_REVIEWS_DELETE": { uri: function(course_id, assignment_id, submission_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + submission_id + "/peer_reviews"}, method: "DELETE" },
  "PEER_REVIEWS_DELETE_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id, submission_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + submission_id + "/peer_reviews"}, method: "DELETE" },
  "POLLING_POLL_SESSIONS": { uri: function(poll_id){return "/api/v1/polls/" + poll_id + "/poll_sessions"}, method: "GET" },
  "POLLING_POLL_SESSION_GET": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_sessions/" + id}, method: "GET" },
  "POLLING_POLL_SESSION_CREATE": { uri: function(poll_id){return "/api/v1/polls/" + poll_id + "/poll_sessions"}, method: "POST" },
  "POLLING_POLL_SESSION_UPDATE": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_sessions/" + id}, method: "PUT" },
  "POLLING_POLL_SESSION_DELETE": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_sessions/" + id}, method: "DELETE" },
  "POLLING_POLL_SESSION_OPEN": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_sessions/" + id + "/open"}, method: "GET" },
  "POLLING_POLL_SESSION_CLOSE": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_sessions/" + id + "/close"}, method: "GET" },
  "POLLING_POLL_SESSION_OPENED": { uri: function(){return "/api/v1/poll_sessions/opened"}, method: "GET" },
  "POLLING_POLL_SESSION_CLOSED": { uri: function(){return "/api/v1/poll_sessions/closed"}, method: "GET" },
  "POLLING_POLL_CHOICES": { uri: function(poll_id){return "/api/v1/polls/" + poll_id + "/poll_choices"}, method: "GET" },
  "POLLING_POLL_CHOICE_GET": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_choices/" + id}, method: "GET" },
  "POLLING_POLL_CHOICE_CREATE": { uri: function(poll_id){return "/api/v1/polls/" + poll_id + "/poll_choices"}, method: "POST" },
  "POLLING_POLL_CHOICE_UPDATE": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_choices/" + id}, method: "PUT" },
  "POLLING_POLL_CHOICE_DELETE": { uri: function(poll_id, id){return "/api/v1/polls/" + poll_id + "/poll_choices/" + id}, method: "DELETE" },
  "POLLING_POLL_SUBMISSION_GET": { uri: function(poll_id, poll_session_id, id){return "/api/v1/polls/" + poll_id + "/poll_sessions/" + poll_session_id + "/poll_submissions/" + id}, method: "GET" },
  "POLLING_POLL_SUBMISSION_CREATE": { uri: function(poll_id, poll_session_id){return "/api/v1/polls/" + poll_id + "/poll_sessions/" + poll_session_id + "/poll_submissions"}, method: "POST" },
  "POLLING_POLLS": { uri: function(){return "/api/v1/polls"}, method: "GET" },
  "POLLING_POLL_GET": { uri: function(id){return "/api/v1/polls/" + id}, method: "GET" },
  "POLLING_POLL_CREATE": { uri: function(){return "/api/v1/polls"}, method: "POST" },
  "POLLING_POLL_UPDATE": { uri: function(id){return "/api/v1/polls/" + id}, method: "PUT" },
  "POLLING_POLL_DELETE": { uri: function(id){return "/api/v1/polls/" + id}, method: "DELETE" },
  "PROGRES_GET": { uri: function(id){return "/api/v1/progress/" + id}, method: "GET" },
  "QUIZZES_QUIZ_ASSIGNMENT_OVERRIDES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/quizzes/assignment_overrides"}, method: "GET" },
  "QUIZZES_QUIZ_EXTENSION_CREATE": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/extensions"}, method: "POST" },
  "QUIZZES_QUIZ_IP_FILTERS": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/ip_filters"}, method: "GET" },
  "QUIZZES_QUIZ_GROUP_GET": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/groups/" + id}, method: "GET" },
  "QUIZZES_QUIZ_GROUP_CREATE": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/groups"}, method: "POST" },
  "QUIZZES_QUIZ_GROUP_UPDATE": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/groups/" + id}, method: "PUT" },
  "QUIZZES_QUIZ_GROUP_DELETE": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/groups/" + id}, method: "DELETE" },
  "QUIZZES_QUIZ_GROUP_REORDER": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/groups/" + id + "/reorder"}, method: "POST" },
  "QUIZZES_QUIZ_QUESTIONS": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/questions"}, method: "GET" },
  "QUIZZES_QUIZ_QUESTION_GET": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/questions/" + id}, method: "GET" },
  "QUIZZES_QUIZ_QUESTION_CREATE": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/questions"}, method: "POST" },
  "QUIZZES_QUIZ_QUESTION_UPDATE": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/questions/" + id}, method: "PUT" },
  "QUIZZES_QUIZ_QUESTION_DELETE": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/questions/" + id}, method: "DELETE" },
  "QUIZZES_QUIZ_REPORTS": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/reports"}, method: "GET" },
  "QUIZZES_QUIZ_REPORT_CREATE": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/reports"}, method: "POST" },
  "QUIZZES_QUIZ_REPORT_GET": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/reports/" + id}, method: "GET" },
  "QUIZZES_QUIZ_REPORT_ABORT": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/reports/" + id}, method: "DELETE" },
  "QUIZZES_QUIZ_STATISTICS": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/statistics"}, method: "GET" },
  "QUIZZES_QUIZ_SUBMISSION_EVENTS_CREATE": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions/" + id + "/events"}, method: "POST" },
  "QUIZZES_QUIZ_SUBMISSION_EVENTS": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions/" + id + "/events"}, method: "GET" },
  "QUIZZES_QUIZ_SUBMISSION_FILE_CREATE": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions/self/files"}, method: "POST" },
  "QUIZZES_QUIZ_SUBMISSION_QUESTIONS": { uri: function(quiz_submission_id){return "/api/v1/quiz_submissions/" + quiz_submission_id + "/questions"}, method: "GET" },
  "QUIZZES_QUIZ_SUBMISSION_QUESTION_ANSWER": { uri: function(quiz_submission_id){return "/api/v1/quiz_submissions/" + quiz_submission_id + "/questions"}, method: "POST" },
  "QUIZZES_QUIZ_SUBMISSION_QUESTION_FLAG": { uri: function(quiz_submission_id, id){return "/api/v1/quiz_submissions/" + quiz_submission_id + "/questions/" + id + "/flag"}, method: "PUT" },
  "QUIZZES_QUIZ_SUBMISSION_QUESTION_UNFLAG": { uri: function(quiz_submission_id, id){return "/api/v1/quiz_submissions/" + quiz_submission_id + "/questions/" + id + "/unflag"}, method: "PUT" },
  "QUIZZES_QUIZ_SUBMISSION_USER_MESSAGE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + id + "/submission_users/message"}, method: "POST" },
  "QUIZZES_QUIZ_SUBMISSIONS": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions"}, method: "GET" },
  "QUIZZES_QUIZ_SUBMISSIONS_GET": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions/" + id}, method: "GET" },
  "QUIZZES_QUIZ_SUBMISSIONS_CREATE": { uri: function(course_id, quiz_id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions"}, method: "POST" },
  "QUIZZES_QUIZ_SUBMISSIONS_UPDATE": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions/" + id}, method: "PUT" },
  "QUIZZES_QUIZ_SUBMISSIONS_COMPLETE": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions/" + id + "/complete"}, method: "POST" },
  "QUIZZES_QUIZ_SUBMISSIONS_TIME": { uri: function(course_id, quiz_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + quiz_id + "/submissions/" + id + "/time"}, method: "GET" },
  "QUIZZES_QUIZZES": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/quizzes"}, method: "GET" },
  "QUIZZES_QUIZZES_GET": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + id}, method: "GET" },
  "QUIZZES_QUIZZES_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/quizzes"}, method: "POST" },
  "QUIZZES_QUIZZES_UPDATE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + id}, method: "PUT" },
  "QUIZZES_QUIZZES_DELETE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + id}, method: "DELETE" },
  "QUIZZES_QUIZZES_REORDER": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + id + "/reorder"}, method: "POST" },
  "QUIZZES_QUIZZES_VALIDATE_ACCESS_CODE": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/quizzes/" + id + "/validate_access_code"}, method: "POST" },
  "ROLE_OVERRIDES": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/roles"}, method: "GET" },
  "ROLE_OVERRIDE_GET": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/roles/" + id}, method: "GET" },
  "ROLE_OVERRIDE_ADD_ROLE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/roles"}, method: "POST" },
  "ROLE_OVERRIDE_REMOVE_ROLE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/roles/" + id}, method: "DELETE" },
  "ROLE_OVERRIDE_ACTIVATE_ROLE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/roles/" + id + "/activate"}, method: "POST" },
  "ROLE_OVERRIDE_UPDATE": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/roles/" + id}, method: "PUT" },
  "SIS_IMPORTS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/sis_imports"}, method: "GET" },
  "SIS_IMPORTS_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/sis_imports"}, method: "POST" },
  "SIS_IMPORTS_GET": { uri: function(account_id, id){return "/api/v1/accounts/" + account_id + "/sis_imports/" + id}, method: "GET" },
  "SISIS_ASSIGNMENTS": { uri: function(account_id){return "/api/sis/accounts/" + account_id + "/assignments"}, method: "GET" },
  "SISIS_ASSIGNMENTS_BY_COURSES_AND_COURSE": { uri: function(course_id){return "/api/sis/courses/" + course_id + "/assignments"}, method: "GET" },
  "SEARCH_RECIPIENTS": { uri: function(){return "/api/v1/conversations/find_recipients"}, method: "GET" },
  "SEARCH_RECIPIENTS_BY_SEARCH_AND_RECIPIENTS": { uri: function(){return "/api/v1/search/recipients"}, method: "GET" },
  "SEARCH_ALL_COURSES": { uri: function(){return "/api/v1/search/all_courses"}, method: "GET" },
  "SECTIONS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/sections"}, method: "GET" },
  "SECTION_CREATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/sections"}, method: "POST" },
  "SECTION_CROSSLIST": { uri: function(id, new_course_id){return "/api/v1/sections/" + id + "/crosslist/" + new_course_id}, method: "POST" },
  "SECTION_UNCROSSLIST": { uri: function(id){return "/api/v1/sections/" + id + "/crosslist"}, method: "DELETE" },
  "SECTION_UPDATE": { uri: function(id){return "/api/v1/sections/" + id}, method: "PUT" },
  "SECTION_GET": { uri: function(id){return "/api/v1/sections/" + id}, method: "GET" },
  "SECTION_DELETE": { uri: function(id){return "/api/v1/sections/" + id}, method: "DELETE" },
  "SERVICES_GET_KALTURA_CONFIG": { uri: function(){return "/api/v1/services/kaltura"}, method: "GET" },
  "SERVICESTART_KALTURA_SESSION": { uri: function(){return "/api/v1/services/kaltura_session"}, method: "POST" },
  "SUBMISSION_COMMENTS_CREATE_FILE": { uri: function(course_id, assignment_id, user_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + user_id + "/comments/files"}, method: "POST" },
  "SUBMISSION_CREATE": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions"}, method: "POST" },
  "SUBMISSION_CREATE_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions"}, method: "POST" },
  "SUBMISSIONS": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions"}, method: "GET" },
  "SUBMISSIONS_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions"}, method: "GET" },
  "SUBMISSIONS_FOR_STUDENTS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/students/submissions"}, method: "GET" },
  "SUBMISSIONS_FOR_STUDENTS_BY_SECTIONS_AND_SECTION": { uri: function(section_id){return "/api/v1/sections/" + section_id + "/students/submissions"}, method: "GET" },
  "SUBMISSIONS_GET": { uri: function(course_id, assignment_id, user_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + user_id}, method: "GET" },
  "SUBMISSIONS_GET_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id, user_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + user_id}, method: "GET" },
  "SUBMISSIONS_CREATE_FILE": { uri: function(course_id, assignment_id, user_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + user_id + "/files"}, method: "POST" },
  "SUBMISSIONS_CREATE_FILE_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id, user_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + user_id + "/files"}, method: "POST" },
  "SUBMISSIONS_UPDATE": { uri: function(course_id, assignment_id, user_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + user_id}, method: "PUT" },
  "SUBMISSIONS_UPDATE_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id, user_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + user_id}, method: "PUT" },
  "SUBMISSIONS_GRADEABLE_STUDENTS": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/gradeable_students"}, method: "GET" },
  "SUBMISSIONS_BULK_UPDATE": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/submissions/update_grades"}, method: "POST" },
  "SUBMISSIONS_BULK_UPDATE_BY_ASSIGNMENTS_AND_ASSIGNMENT": { uri: function(course_id, assignment_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/update_grades"}, method: "POST" },
  "SUBMISSIONS_BULK_UPDATE_BY_SECTIONS_AND_SECTION": { uri: function(section_id){return "/api/v1/sections/" + section_id + "/submissions/update_grades"}, method: "POST" },
  "SUBMISSIONS_BULK_UPDATE_BY_SECTIONS_AND_SECTION_AND_ASSIGNMENTS_AND_ASSIGNMENT": { uri: function(section_id, assignment_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/update_grades"}, method: "POST" },
  "SUBMISSIONS_MARK_SUBMISSION_READ": { uri: function(course_id, assignment_id, user_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + user_id + "/read"}, method: "PUT" },
  "SUBMISSIONS_MARK_SUBMISSION_READ_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id, user_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + user_id + "/read"}, method: "PUT" },
  "SUBMISSIONS_MARK_SUBMISSION_UNREAD": { uri: function(course_id, assignment_id, user_id){return "/api/v1/courses/" + course_id + "/assignments/" + assignment_id + "/submissions/" + user_id + "/read"}, method: "DELETE" },
  "SUBMISSIONS_MARK_SUBMISSION_UNREAD_BY_SECTIONS_AND_SECTION": { uri: function(section_id, assignment_id, user_id){return "/api/v1/sections/" + section_id + "/assignments/" + assignment_id + "/submissions/" + user_id + "/read"}, method: "DELETE" },
  "TABS": { uri: function(course_id){return "/api/v1/courses/" + course_id + "/tabs"}, method: "GET" },
  "TABS_BY_GROUPS_AND_GROUP": { uri: function(group_id){return "/api/v1/groups/" + group_id + "/tabs"}, method: "GET" },
  "TAB_UPDATE": { uri: function(course_id, tab_id){return "/api/v1/courses/" + course_id + "/tabs/" + tab_id}, method: "PUT" },
  "USER_OBSERVEES": { uri: function(user_id){return "/api/v1/users/" + user_id + "/observees"}, method: "GET" },
  "USER_OBSERVEE_CREATE": { uri: function(user_id){return "/api/v1/users/" + user_id + "/observees"}, method: "POST" },
  "USER_OBSERVEE_GET": { uri: function(user_id, observee_id){return "/api/v1/users/" + user_id + "/observees/" + observee_id}, method: "GET" },
  "USER_OBSERVEE_UPDATE": { uri: function(user_id, observee_id){return "/api/v1/users/" + user_id + "/observees/" + observee_id}, method: "PUT" },
  "USER_OBSERVEE_DELETE": { uri: function(user_id, observee_id){return "/api/v1/users/" + user_id + "/observees/" + observee_id}, method: "DELETE" },
  "USERS": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/users"}, method: "GET" },
  "USER_ACTIVITY_STREAM": { uri: function(){return "/api/v1/users/activity_stream"}, method: "GET" },
  "USER_ACTIVITY_STREAM_SUMMARY": { uri: function(){return "/api/v1/users/self/activity_stream/summary"}, method: "GET" },
  "USER_TODO_ITEMS": { uri: function(){return "/api/v1/users/self/todo"}, method: "GET" },
  "USER_UPCOMING_EVENTS": { uri: function(){return "/api/v1/users/self/upcoming_events"}, method: "GET" },
  "USER_MISSING_SUBMISSIONS": { uri: function(user_id){return "/api/v1/users/" + user_id + "/missing_submissions"}, method: "GET" },
  "USER_IGNORE_STREAM_ITEM": { uri: function(id){return "/api/v1/users/self/activity_stream/" + id}, method: "DELETE" },
  "USER_IGNORE_ALL_STREAM_ITEMS": { uri: function(){return "/api/v1/users/self/activity_stream"}, method: "DELETE" },
  "USER_CREATE_FILE": { uri: function(user_id){return "/api/v1/users/" + user_id + "/files"}, method: "POST" },
  "USER_SHOW": { uri: function(id){return "/api/v1/users/" + id}, method: "GET" },
  "USER_CREATE": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/users"}, method: "POST" },
  "USER_CREATE_SELF_REGISTERED_USER": { uri: function(account_id){return "/api/v1/accounts/" + account_id + "/self_registration"}, method: "POST" },
  "USER_SETTINGS": { uri: function(id){return "/api/v1/users/" + id + "/settings"}, method: "PUT" },
  "USER_GET_CUSTOM_COLORS": { uri: function(id){return "/api/v1/users/" + id + "/colors"}, method: "GET" },
  "USER_GET_CUSTOM_COLOR": { uri: function(id, asset_string){return "/api/v1/users/" + id + "/colors/" + asset_string}, method: "GET" },
  "USER_SET_CUSTOM_COLOR": { uri: function(id, asset_string){return "/api/v1/users/" + id + "/colors/" + asset_string}, method: "PUT" },
  "USER_UPDATE": { uri: function(id){return "/api/v1/users/" + id}, method: "PUT" },
  "USER_MERGE_INTO": { uri: function(id, destination_user_id){return "/api/v1/users/" + id + "/merge_into/" + destination_user_id}, method: "PUT" },
  "USER_MERGE_INTO_BY_ACCOUNTS_AND_DESTINATION_ACCOUNT": { uri: function(id, destination_account_id, destination_user_id){return "/api/v1/users/" + id + "/merge_into/accounts/" + destination_account_id + "/users/" + destination_user_id}, method: "PUT" },
  "PROFILE_SETTINGS": { uri: function(user_id){return "/api/v1/users/" + user_id + "/profile"}, method: "GET" },
  "PROFILE_PROFILE_PICS": { uri: function(user_id){return "/api/v1/users/" + user_id + "/avatars"}, method: "GET" },
  "PAGE_VIEWS": { uri: function(user_id){return "/api/v1/users/" + user_id + "/page_views"}, method: "GET" },
  "CUSTOM_DATA_SET_DATA": { uri: function(user_id){return "/api/v1/users/" + user_id + "/custom_data(/*scope)"}, method: "PUT" },
  "CUSTOM_DATA_GET_DATA": { uri: function(user_id){return "/api/v1/users/" + user_id + "/custom_data(/*scope)"}, method: "GET" },
  "CUSTOM_DATA_DELETE_DATA": { uri: function(user_id){return "/api/v1/users/" + user_id + "/custom_data(/*scope)"}, method: "DELETE" },
  "COURSE_NICKNAMES": { uri: function(){return "/api/v1/users/self/course_nicknames"}, method: "GET" },
  "COURSE_NICKNAME_GET": { uri: function(course_id){return "/api/v1/users/self/course_nicknames/" + course_id}, method: "GET" },
  "COURSE_NICKNAME_UPDATE": { uri: function(course_id){return "/api/v1/users/self/course_nicknames/" + course_id}, method: "PUT" },
  "COURSE_NICKNAME_DELETE": { uri: function(course_id){return "/api/v1/users/self/course_nicknames/" + course_id}, method: "DELETE" },
  "COURSE_NICKNAME_CLEAR": { uri: function(){return "/api/v1/users/self/course_nicknames"}, method: "DELETE" },
  "EPUB_EXPORT_GET": { uri: function(course_id, id){return "/api/v1/courses/" + course_id + "/epub_exports/" + id}, method: "GET" },

};
